name: CI
on: [push, pull_request]
env:
  CI: true
  SCALA_VERSION: 2.12.12 # Used only for Doc Site
jobs:
  validate:
    name: Scala ${{ matrix.scala }}, Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [adopt@1.8, adopt@1.11, adopt@1.14]
        scala: [2.12.12, 2.13.3]
    env:
      SCALA_VERSION: ${{ matrix.scala }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - uses: coursier/cache-action@v3
      - name: Compile
        run: csbt ++$SCALA_VERSION test:compile
      #- name: Check compatibility
      #  run: csbt ++$SCALA_VERSION mimaReportBinaryIssues
      - name: Test
        run: csbt ++$SCALA_VERSION test
      - name: Scaladoc
        run: csbt ++$SCALA_VERSION doc
  docs:
    name: Doc Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - uses: coursier/cache-action@v3
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install Jekyll
        run: |
          gem install bundler
          bundle install --gemfile=docs/Gemfile
      - name: Build project site
        run: csbt ++$SCALA_VERSION docs/makeMicrosite
